apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default  # namespace, where k8s application manifests will be deployed
    server: https://kubernetes.default.svc
  project: default  
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD  # will deploy the latest commit from git repository