apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-with-https
  namespace: argocd
spec:
  project: team-finance  # appProject resource, which applies restrictions
  source:
    repoURL: https://github.com/anuroopps2001/argocd-example-apps-labs.git
    targetRevision: HEAD  # asking argocd to look into the latest git commit apply the manifests of that commit
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: finance
