apiVersion: batch/v1
kind: Job
metadata:
  name: job-first
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - "sh"
            - "-c"
            - "echo 'Trying to connect to $DB_HOST..'; sleep 5; echo 'Connected..!!'"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: database_host
