apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anuroopps2001/argocd-example-apps-labs.git
    targetRevision: HEAD  # asking argocd to look into the latest git commit apply the manifests of that commit
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default # namespace, where k8s manifests will be deployed
  syncPolicy:
    automated:     # enabled auto sync on argocd
      prune: true  # enables pruning to delete the resources that are not present in source but present in cluster. Pruning is part of sync process
