apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/anuroopps2001/argocd-private-repos.git
  password: hp_ne<REDACTED>kL # should be PAT
  username: anuroopps2001
  project: default
