apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:anuroopps2001/argocd-private-repos.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA+b80kdp0UcONR7meJ7CvyfrUXqMh7oqayKh8QUPlUUgAAAKjN5pttzeab
    bQAAAAtzc2gtZWQyNTUxOQAAACA+b80kdp0UcONR7meJ7CvyfrUXqMh7oqayKh8QUPlUUg
    AAAEDf9gG1mgjc6kf/uOxrbbXNWyDcEngYMQNSuqq0s+JcUj5vzSR2nRRw41HuZ4nsK/J+
    tReoyHuiprIqHxBQ+VRSAAAAIWF6dXJldXNlckBhenVyZS1tb25pdG9yLWNsaWVudC12bQ
    ECAwQ=
    -----END OPENSSH PRIVATE KEY-----
