apiVersion: batch/v1
kind: Job
metadata:
  name: presync-hook-job
  annotations:
    argocd.argoproj.io/hook: PreSync  # defines this job as PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation  #HookSucceeded  # condition, when this job will be created
spec:
  backoffLimit: 2 # max time job can try run in case of failures
  template:
    spec: 
      restartPolicy: Never  # never restart the pod incase of failures
      containers:
        - name: presync-hook-container
          image: busybox
          command:
            - "sh"
            - "-c"
            - "echo 'Running sample job...'; sleep 10; echo 'Done'"
